-- Add missing columns to recipes_in_meal_plan table
ALTER TABLE recipes_in_meal_plan 
ADD COLUMN IF NOT EXISTS serving_size DECIMAL(5,2) NOT NULL DEFAULT 1.00,
ADD COLUMN IF NOT EXISTS "order" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN IF NOT EXISTS is_frozen BOOLEAN DEFAULT TRUE,
ADD COLUMN IF NOT EXISTS is_completed BOOLEAN DEFAULT FALSE,
ADD COLUMN IF NOT EXISTS completed_at TIMESTAMP DEFAULT NULL;